image:
  repository: registry.ustpace.com/docker-sandbox/vdcheckdeploy-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdcheckdeploy-backend-habitat-testttttttttttttttttttttttttttttttttttttttttttttttttttt.dagility.com
    paths:
    - /
serviceAccount:
  create: false
